### ISSUE TITLE
Tag stable version for ZF3 compat

### ISSUE THREAD

**Issue by exptom** [ZF-Commons/zfc-rbac#348]
master currently supports ZF3 and I am using it in a project successfully. Is it possible to get it tagged so that I don't have to rely on a dev version in composer.json?

Thanks :)

**Comment by bakura10** [comment]
Hi,

Thanks. I'm thinking of tagging master as 2.6.0 (version 3 still in development is the develop branch). @danizord any objection on that?

**Comment by cincarnato** [comment]
+1

**Comment by bakura10** [comment]
I've just tried to pull the latest code and run the tests and I'm having +67 errors, apparently due to module manager, which is a bit strange...

I'll therefore need to delay that for now to dig into the issue. If someone can also try to pull the dev-master, and try to run the tests to see what is happening that would help as well.

@danizord are you able to reproduce this issue?

**Comment by webimpress** [comment]
@bakura10 please see my PR #349

**Comment by bakura10** [comment]
I'm happy to say that ZfcRbac has been tagged to 2.6.0 :). Thanks a lot!

I will open another issue in a few seconds for looking for a new leader for this project!

**Comment by exptom** [comment]
Thank you :)
